language: python

python: 2.7

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
    - env: TOX_ENV=py27-mp
    - env: TOX_ENV=py33-mp
    - env: TOX_ENV=py34-mp
    - env: TOX_ENV=py27-urllib3
    - env: TOX_ENV=py33-urllib3
    - env: TOX_ENV=py34-urllib3

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py27-mp
  - TOX_ENV=py33-mp
  - TOX_ENV=py34-mp
  - TOX_ENV=py27-urllib3
  - TOX_ENV=py33-urllib3
  - TOX_ENV=py34-urllib3

services:
  - mongodb
  - redis-server

install:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - pip install tox

before_script:
  - mysql -e 'create database spider_test'
  - psql -c 'create database spider_test' -U postgres

script:
    # Override test settings with travis settings 
    - cp travis_settings.py test_settings_local.py
    # Run tests and find out the test coverage
    - tox -e $TOX_ENV

after_success:
  - coveralls
